# Generated by Django 5.0.6 on 2024-06-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sticky_notes_app", "0002_board_poster_board"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poster",
            name="board",
        ),
        migrations.DeleteModel(
            name="Board",
        ),
    ]
