# Generated by Django 5.0.6 on 2024-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sticky_notes_app", "0005_poster_temp_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poster",
            name="temp_author",
        ),
        migrations.AlterField(
            model_name="poster",
            name="author",
            field=models.CharField(max_length=50),
        ),
    ]
