# Generated by Django 5.0.6 on 2024-06-12 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sticky_notes_app", "0006_remove_poster_temp_author_alter_poster_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sticky_notes_app.author",
            ),
        ),
    ]
