# Generated by Django 5.0.6 on 2024-06-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sticky_notes_app", "0007_alter_poster_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="priority",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Low",
                max_length=50,
            ),
        ),
    ]
